---
title: "BDC_Tracking"
output: pdf_document
date: '2022-04-05'
---


```{r}
library("rjson")
library("jsonlite")
library("tidyverse")
library("snowfall")
library("gganimate") # For turning ggplot's into animations

#setwd("/Volumes/BRICK_HOUSE/Hockey/Big-Data-Cup-2022-Private-main/TrackingData")
setwd("H:/Hockey/Big-Data-Cup-2022-Private-main/TrackingData")
json_file <- "BDC_2022_all_data.json"
dat <- fromJSON(json_file)
```
```{r}
library(snowfall)
paraLapply = function(arr,fn,cores)
{
  
  sfInit(parallel=TRUE,cpus=cores) ## change to 4,8 w/e
  
  fun = function(){x = sfLapply( x=arr, fun=fn ) ; x}
  sfExportAll()
  
  res = fun() ;
  
  sfRemoveAll( ) 	## If you break the function (using control+C), you should
  sfStop() 		## run these commands unless you really like having zero RAM (hardcore memory leakzz)
  res ;
}
```

```{r}
r=0
t_start=7
t_end=8
line1 <- paste('dat$relevant_events$\'',r,'\'$tracks$\'',t_start,'\'',sep='')
line2 <- eval(parse(text=line1))
if(length(line2$frame_id)!=0){
  json_tracks <- lapply(line2, function(x) {
    x[sapply(x, is.null)] <- NA
    unlist(x)
  })
  current_track <- as.data.frame(do.call("cbind", json_tracks))
}
 
for(t in (t_start+1):t_end){
  line1 <- paste('dat$relevant_events$\'',r,'\'$tracks$\'',t,'\'',sep='')
  line2 <- eval(parse(text=line1))
  if(length(line2$frame_id)!=0){
    json_tracks <- lapply(line2, function(x) {
      x[sapply(x, is.null)] <- NA
      unlist(x)
    })
    current_track <- rbind(current_track,as.data.frame(do.call("cbind", json_tracks)))
  }
}
current_track %>% View()

current_track$frame_id = current_track$frame_id %>% as.integer()
current_track$period = current_track$period %>% as.integer()
current_track$track_id = current_track$track_id %>% as.integer()
current_track$jersey_number = current_track$jersey_number %>% as.integer()
current_track$x_ft = current_track$x_ft %>% as.double()
current_track$y_ft = current_track$y_ft %>% as.double()
```

```{r}
test=current_track %>% filter(track_id==2)
plot(test$x_ft,test$y_ft)
current_track$frame_id %>% unique() %>% length() #approx 8 seconds

tracking_data = read.csv("https://raw.githubusercontent.com/bigdatacup/Big-Data-Cup-2021/main/TrackingData/2022-02-14%20Finland%20at%20USA/2022-02-14%20Finland%20at%20USA%20P3%20PP6.csv")
test=tracking_data %>% filter(track_id==1)
plot(test$x_ft,test$y_ft)
tracking_data$frame_id %>% unique() %>% length() #approx 15 seconds
```

```{r}
#Other guys data
r=0
t=7
setwd("H:/Hockey/Big-Data-Cup-2022-Private-main/TrackingData")
current_track2 <- read_csv("bdc-main/data/2022-02-08 Canada at USA/2022-02-08 Canada at USA P1 PP1.csv")
current_track2$frame_id = current_track2$frame_id %>% as.integer()
current_track2$period = current_track2$period %>% as.integer()
current_track2$track_id = current_track2$track_id %>% as.integer()
current_track2$jersey_number = current_track2$jersey_number %>% as.integer()
current_track2$x_ft = current_track2$x_ft %>% as.double()
current_track2$y_ft = current_track2$y_ft %>% as.double()

current_track3 <- current_track2 %>% filter(frame_id<615 & frame_id>374)

```

```{r}
# Load the data directly from github
# To get this URL go to our GitHub repository then click "TrackingData/<game name>/<powerplay name.csv>", click "Raw", then copy the url once the raw data loads
#tracking_data = current_track
tracking_data = current_track3 %>% filter(jersey_number==19)
#read.csv("https://raw.githubusercontent.com/bigdatacup/Big-Data-Cup-2021/main/TrackingData/2022-02-14%20Finland%20at%20USA/2022-02-14%20Finland%20at%20USA%20P3%20PP6.csv")


## DATA WRANGLING WITH NEST AND MAP ##

# The nest and map functions are a huge help in making sense of tracking data and performing frame-by-frame operations

# Using group_by and nest in R allows us to split data into smaller more manageable sub-data frames
tracking_data_nested = tracking_data %>%
  group_by(frame_id) %>%
  nest()


# We can perform transformations on the nested data using mutate and map
tracking_data_player_count = tracking_data_nested %>%
  mutate(num_players = map(.x = data, .f = ~nrow(.x)))




## ANIMATED PLOTS ##

# Set the specs for the gif we want to create (lower res to make it run quicker)
options(gganimate.dev_args = list(width = 10, height = 6, units = 'in', res = 320))

# Source in the plot_rink function
source("H:/Hockey/Big-Data-Cup-2022-Private-main/OTTHAC_Tutorial/Code/plot_rink.R")
#source("/Volumes/BRICK_HOUSE/Hockey/Big-Data-Cup-2022-Private-main/OTTHAC_Tutorial/Code/plot_rink.R")

# Create a gif of this play
p = plot_rink(ggplot(tracking_data)) +
  geom_point(aes(x = x_ft, y = y_ft, fill = team_name), shape = 21, size = 6) +
  geom_text(aes(x = x_ft, y = y_ft, label = track_id, colour = team_name), size = 3) +
  scale_colour_manual(values = c("USA" = "white", "Finland" = "white")) +
  scale_fill_manual(values = c("USA" = "blue", "Finland" = "red")) +
  transition_time(frame_id) +
  labs(fill = "Team") +
  guides(colour = "none")


# Get the maximum and minimum frame number (so we know how long the gif should be)
max_frame = tracking_data$frame_id %>% max()
min_frame = tracking_data$frame_id %>% min() 


# Render the animation

title = paste("Figures/PP", r, "_", unique(tracking_data$team_name)[1], "_", unique(tracking_data$team_name)[2], "_SS", t, sep = "")

if(type == "mp4"){
  # Save as mp4
  p2 = animate(p, renderer = ffmpeg_renderer(), fps = 30, duration = (max_frame - min_frame)/30 + 1)
  anim_save(paste(title,"2.mp4",sep=""), p2)
}else{
  #Save as gif
  anim_save(paste(title,".gif",sep=""), p, fps = 30, duration = (max_frame - min_frame)/30 + 1)
}



```

```{r}
save_play <- function(t_start){#r,t_start,t_end,type){
  r=0
  library("rjson")
  library("jsonlite")
  library("tidyverse")
  library("gganimate")
  line1 <- paste('dat$relevant_events$\'',r,'\'$tracks$\'',t_start,'\'',sep='')
  line2 <- eval(parse(text=line1))
  if(length(line2$frame_id)!=0){
    json_tracks <- lapply(line2, function(x) {
      x[sapply(x, is.null)] <- NA
      unlist(x)
    })
    tracking_data <- as.data.frame(do.call("cbind", json_tracks))
    teams <- unique(tracking_data$team_name)
  team1 <- teams[1]
  team2 <- teams[2]
  title = paste("Figures/PP", r, "_", team1, "_", team2, "_SS", t_start, sep = "")

  #if(t_start!=t_end){
   # title = paste("Figures/PP", r, "_", unique(tracking_data$team_name)[1], "_", unique(tracking_data$team_name)[2], "_SS", t_start,"_",t_end, sep = "")
    #for(t in (t_start+1):t_end){
     # line1 <- paste('dat$relevant_events$\'',r,'\'$tracks$\'',t,'\'',sep='')
      #line2 <- eval(parse(text=line1))
      #if(length(line2$frame_id)!=0){
       # json_tracks <- lapply(line2, function(x) {
        #  x[sapply(x, is.null)] <- NA
         # unlist(x)
        #})
        #tracking_data <- rbind(tracking_data,as.data.frame(do.call("cbind", json_tracks)))
      #}
    #}
  #}
  
  tracking_data$frame_id = tracking_data$frame_id %>% as.integer()
  tracking_data$period = tracking_data$period %>% as.integer()
  tracking_data$track_id = tracking_data$track_id %>% as.integer()
  tracking_data$jersey_number = tracking_data$jersey_number %>% as.integer()
  tracking_data$x_ft = tracking_data$x_ft %>% as.double()
  tracking_data$y_ft = tracking_data$y_ft %>% as.double()
  
  # Using group_by and nest in R allows us to split data into smaller more manageable sub-data frames
  tracking_data_nested = tracking_data %>%
    group_by(frame_id) %>%
    nest()
  
  
  # We can perform transformations on the nested data using mutate and map
  tracking_data_player_count = tracking_data_nested %>%
    mutate(num_players = map(.x = data, .f = ~nrow(.x)))
  
  
  
  
  ## ANIMATED PLOTS ##
  
  # Set the specs for the gif we want to create (lower res to make it run quicker)
  options(gganimate.dev_args = list(width = 10, height = 6, units = 'in', res = 320))
  
  # Source in the plot_rink function
  source("H:/Hockey/Big-Data-Cup-2022-Private-main/OTTHAC_Tutorial/Code/plot_rink.R")
  #source("/Volumes/BRICK_HOUSE/Hockey/Big-Data-Cup-2022-Private-main/OTTHAC_Tutorial/Code/plot_rink.R")
  
  # Create a gif of this play
  p = plot_rink(ggplot(tracking_data)) +
    geom_point(aes(x = x_ft, y = y_ft, fill = team_name), shape = 21, size = 6) +
    geom_text(aes(x = x_ft, y = y_ft, label = track_id, colour = team_name), size = 3) +
    scale_colour_manual(values = c("USA" = "white", "Canada" = "white")) +
    scale_fill_manual(values = c("USA" = "blue", "Canada" = "red")) +
    transition_time(frame_id) +
    labs(fill = "Team") +
    guides(colour = "none")
  
  
  # Get the maximum and minimum frame number (so we know how long the gif should be)
  max_frame = tracking_data$frame_id %>% max()
  min_frame = tracking_data$frame_id %>% min() 
  
  # Render the animation
  #if(type == "mp4"){
    # Save as mp4
    p2 = animate(p, renderer = ffmpeg_renderer(), fps = 30, duration = (max_frame - min_frame)/30 + 1)
    anim_save(paste(title,".mp4",sep=""), p2)
  #}else{
    #Save as gif
   # anim_save(paste(title,".gif",sep=""), p, fps = 30, duration = (max_frame - min_frame)/30 + 1)
  #}
  }
}
```

```{r}
plays <- 0:64
aa <- paraLapply(plays, save_play, 4)
```

