---
title: "BDC_2022"
output: pdf_document
---

```{r}
load.libraries = c("rjson", "jsonlite", "tidyverse", "gganimate", "ggpmisc", "ggnewscale", "viridis", "tictoc", "scales", "ggforce", "cowplot")
install.lib = load.libraries[!load.libraries %in% installed.packages()]
for (libs in install.lib) {install.packages(libs, dependencies = TRUE)}
sapply(load.libraries, require, character = TRUE)

#time_step = seq(0.01,10,0.01) #extra fine scale
time_step = seq(0.05,10,0.05) #regular scale
#theta_scale = 0.01 #extra fine scale
theta_scale = 0.05 #regular scale
#speed_puck = 90 #ft/s
speed_puck = 55 #ft/s
#speed_puck = 40 #ft/s

#source("C:/Users/thepi/OneDrive/Documents/Python/Hockey/Big-Data-Cup-2022-Private/code/visualization/hockey_pipeline.R")
#setwd("C:/Users/thepi/OneDrive/Documents/Python/Hockey/Big-Data-Cup-2022-Private")
source("C:/Users/Paula/Desktop/Big-Data-Cup-2022-Private/code/visualization/hockey_pipeline.R")
setwd("C:/Users/Paula/Desktop/Big-Data-Cup-2022-Private")
#json_file <- "data/BDC_2022_all_data.json"
#json_file <- "data/BDC_2022_all_direct_wFrames.json"
json_file <- "data/BDC_2022_passOnly.json"
dat <- fromJSON(json_file)

# Set up the event data to be in a data frame. 
json_events <- lapply(dat[1:28], function(x) {
  x[sapply(x, is.null)] <- NA
  unlist(x)
})
current_event <- as.data.frame(do.call("cbind", json_events))
current_event$team_name[current_event$team_name=="Olympic (Women) - Canada"]="Canada"
current_event$team_name[current_event$team_name=="Olympic (Women) - United States"]="USA"
current_event$team_name[current_event$team_name=="Olympic (Women) - Finland"]="Finland"
current_event$team_name[current_event$team_name=="Olympic (Women) - Olympic Athletes from Russia"]="ROC"
current_event$team_name[current_event$team_name=="Olympic (Women) - Switzerland"]="Switzerland"

current_event$x_coord = current_event$x_coord %>% as.double()
current_event$y_coord = current_event$y_coord %>% as.double()
current_event$x_coord_2 = current_event$x_coord_2 %>% as.double()
current_event$y_coord_2 = current_event$y_coord_2 %>% as.double()

wrong_x <- current_event$x_coord<100

current_event$x_coord[wrong_x] = 200-current_event$x_coord[wrong_x]
current_event$x_coord_2[wrong_x] = 200-current_event$x_coord_2[wrong_x]

current_event$y_coord[!wrong_x] = 85-current_event$y_coord[!wrong_x]
current_event$y_coord_2[!wrong_x] = 85-current_event$y_coord_2[!wrong_x]


vel_ang = calc_vmag_ang(current_event)
current_event$vel_init = vel_ang[,1]
current_event$ang_init = vel_ang[,2]

```

```{r}
#r=0 # powerplay of interest
t_track=233 # 11, 393, 406 is right before a goal, 221 passer not in view
#69 is the first images I shared
speed_puck = current_event$vel_init[t_track]
line1 <- paste('dat$tracks$\'',(t_track-1),'\'',sep='')
line2 <- eval(parse(text=line1))
if(length(line2$frame_id)!=0){
  json_tracks <- lapply(line2, function(x) {
    x[sapply(x, is.null)] <- NA
    unlist(x)
  })
  current_track <- as.data.frame(do.call("cbind", json_tracks))
}
current_track$frame_id = current_track$frame_id %>% as.integer()
current_track$period = current_track$period %>% as.integer()
current_track$track_id = current_track$track_id %>% as.integer()
current_track$jersey_number = current_track$jersey_number %>% as.integer()
current_track$x_ft = current_track$x_ft %>% as.double()
current_track$y_ft = current_track$y_ft %>% as.double()
current_track$vel_x = current_track$vel_x %>% as.double()
current_track$vel_y = current_track$vel_y %>% as.double()

current_track$vel_x[which(current_track$vel_x==0)]=0.05
current_track$vel_y[which(current_track$vel_y==0)]=0.05
current_track$goalie = ifelse(current_track$goalie =='TRUE',T,F)

if(current_track$x_ft[1]<100){
  current_track$x_ft = 200 - current_track$x_ft
  current_track$vel_x = -current_track$vel_x
  current_track$y_ft = 85 - current_track$y_ft
  current_track$vel_y = -current_track$vel_y
}

current_track <- fill_missing_players(current_event[t_track,],current_track)

event_info <- current_event[t_track,] %>% select(team_name,Player_1_num,Player_2_num)
off <- event_info$team_name
puck = current_track[current_track$jersey_number==event_info$Player_1_num,] %>% select(team_name,x_ft,y_ft)
puck = puck[puck$team_name==off,]

n_players <- table(current_track$team_name)
n_off <- sum(n_players[names(n_players)==off])
n_def <- sum(n_players[names(n_players)!=off])
```

```{r}
x_p = current_event[t_track,"x_coord"]#puck$x_ft
y_p = current_event[t_track,"y_coord"]#puck$y_ft

if(abs(y_p-puck$y_ft)>20){
  y_p = 85-y_p
}

theta = seq(-pi,pi,by=theta_scale)
passes = data.frame(angle=c(),x=c(),y=c(), t=c())
for(angle in theta){
  passes = rbind(passes,cbind(angle,puck_motion_model2(x_p,y_p,angle)))
}
new_pass <- clean_pass(passes)
new_pass <- filter_inside_boards(new_pass)

calc_pass <- new_pass %>% group_by(angle) %>% top_n(1, t)

new_pass <- rbind(new_pass,c(new_pass$angle[1],x_p,y_p,0))

xyt <- new_pass %>% select(x,y,t)
loc_vel <- current_track %>% mutate(team_label = ifelse(team_name == off,1,-1)) %>%
  select(x_ft,y_ft,vel_x,vel_y, team_label, goalie) 
# options(warn=-1)
new_pass <- new_pass %>% 
  mutate(all_ctrl = teamwise_ice_ctrl_xyt(loc_vel, xyt), score_prob = apply(xyt,1,score_prob)) %>%
  mutate(pass_value = score_prob * ((all_ctrl+1)/2)^1)
```


```{r}
# Create image of this frame with potential passes
plot_rink(ggplot(current_track)) +
  geom_point(aes(x = x_ft, y = y_ft, fill = team_name), size = 5, shape = 21) +
  geom_text(aes(x = x_ft, y = y_ft, label = jersey_number, colour = team_name), size = 3) +
  geom_point(aes(x = x_p, y = y_p), size = 2, shape = 16, colour='black') +
  geom_segment(aes(x = x_p, y = y_p, xend = puck$x_ft, yend = puck$y_ft),size=1.5, colour='brown')+
  geom_point(data = new_pass, aes(x = x, y = y), size = 1, shape = 4) +
  scale_colour_manual(values = c("Switzerland" = "white", "Finland" = "white")) +
  scale_fill_manual(values = c("Switzerland" = "red", "Finland" = "blue")) +
  labs(fill = "Team") +
  guides(colour = "none")+ 
  geom_segment(aes(x = x_ft, y = y_ft, xend = x_ft+vel_x, yend = y_ft+vel_y), #/sqrt(vel_x^2+vel_y^2) to get r=1
                  arrow = arrow(length = unit(0.2, "cm")),size=1, colour='cyan')
plot_rink(ggplot(current_track)) +
  geom_point(aes(x = x_ft, y = y_ft, fill = team_name), size = 5, shape = 21) +
  geom_text(aes(x = x_ft, y = y_ft, label = jersey_number, colour = team_name), size = 3) +
  geom_point(aes(x = x_p, y = y_p), size = 2, shape = 16, colour='black') +
  geom_point(data = calc_pass, aes(x = x, y = y), size = 1, shape = 4) +
  geom_segment(aes(x = x_p, y = y_p, xend = puck$x_ft, yend = puck$y_ft),size=1.5, colour='brown')+
  scale_colour_manual(values = c("Switzerland" = "white", "Finland" = "white")) +
  scale_fill_manual(values = c("Switzerland" = "red", "Finland" = "blue")) +
  labs(fill = "Team") +
  guides(colour = "none")+ 
  geom_segment(aes(x = x_ft, y = y_ft, xend = x_ft+vel_x, yend = y_ft+vel_y), #/sqrt(vel_x^2+vel_y^2) to get r=1
                  arrow = arrow(length = unit(0.2, "cm")),size=1, colour='cyan')
```

```{r}
which(is.na(new_pass$all_ctrl))
```

```{r}
#angle_pass <- calc_pass[81,]
#point_val = probs_to_point(x_p,y_p,angle_pass,new_pass,current_track,off,TRUE)

observed_angle_pass <- calc_pass[which.min(abs(calc_pass$angle-current_event[t_track,"ang_init"])),]
point_val = probs_to_point(x_p,y_p,observed_angle_pass,new_pass,current_track,off,TRUE)
point_val[[1]]

#pdf("C:/Users/Paula/Desktop/Big-Data-Cup-2022-Private/images/angle_track406.pdf")
point_val[[2]]
#dev.off()
```

```{r}
pdf("C:/Users/Paula/Desktop/Big-Data-Cup-2022-Private/images/fullpass_track406.pdf")
plot_half_rink(ggplot(current_track)) +
      geom_segment(aes(x = x_ft, y = y_ft, xend = x_ft+vel_x, yend = y_ft+vel_y), #/sqrt(vel_x^2+vel_y^2) to get r=1
                   arrow = arrow(length = unit(0.2, "cm")),size=1, colour='cyan') + 
        geom_segment(aes(x = x_p, y = y_p, xend = puck$x_ft, yend = puck$y_ft),size=1.5, colour='brown')+
  geom_point(aes(x = x_ft, y = y_ft, fill = team_name), size = 5, shape = 21) +
      geom_text(aes(x = x_ft, y = y_ft, label = jersey_number, colour = team_name), size = 3) +
      geom_segment(aes(x = x_p, y = y_p, xend = current_event[t_track,"x_coord_2"], yend = current_event[t_track,"y_coord_2"]),colour='dark grey',size = 1,arrow = arrow(length = unit(0.03, "npc")))+
  geom_point(aes(x = x_p, y = y_p), size = 2, shape = 16, colour='black') + 
  #geom_point(data = points, aes(x = x, y = y), colour='dark grey',size = 1, shape = 16) +
      scale_colour_manual(values = c("Switzerland" = "white", "Finland" = "white")) +
  scale_fill_manual(values = c("Switzerland" = "red", "Finland" = "blue")) +
      #geom_segment(data = points,aes(x = x_puck, y = y_puck, xend = x, yend = y),linetype=2)+
      #geom_point(data = points, aes(x = x, y = y), size = 2, shape = 4, colour='dark grey') + 
      labs(fill = "Team") +
  guides(colour = "none")
dev.off()
```

```{r}
all_point_val <- apply(calc_pass,1,probs_to_point,x_puck=x_p,y_puck=y_p,all_ang=new_pass,tracks1=current_track,offence=off,want_plot=FALSE)

pass_potential <- bind_rows(all_point_val, .id = "column_label")
pass_potential


#pass_potential$pass_good = pass_potential$pass_good %>% rescale()
```

```{r}
p <- ggplot(data = pass_potential,aes(x = x, y = y)) + 
    geom_point(aes(color = all_ctrl),size=1, shape=16) +
    scale_colour_gradient2(na.value="white",low = muted("red"), mid = "white", high = muted("blue"))+#,midpoint = 0.5
    scale_x_continuous(expand = c(0, 0)) +
    scale_y_continuous(expand = c(0, 0)) +
  #geom_point(aes(x = x, y = y), size = 1, shape = 4)+
  new_scale_fill() +
  new_scale_color() +
  geom_segment(data=current_track,aes(x = x_ft, y = y_ft, xend = x_ft+vel_x, yend = y_ft+vel_y), #/sqrt(vel_x^2+vel_y^2) to get r=1
  arrow = arrow(length = unit(0.2, "cm")),size=1, colour='cyan')+
  geom_segment(aes(x = x_p, y = y_p, xend = puck$x_ft, yend = puck$y_ft),size=1.5, colour='brown')+
  geom_point(aes(x = x_p, y = y_p), size = 2, shape = 16, colour='black') +
  geom_point(data=current_track,aes(x = x_ft, y = y_ft, fill = team_name), size = 5, shape = 21) +
  geom_text(data=current_track,aes(x = x_ft, y = y_ft, label = jersey_number, colour = team_name), size = 3) +
  scale_colour_manual(values = c("Switzerland" = "white", "Finland" = "white")) +
  scale_fill_manual(values = c("Switzerland" = "red", "Finland" = "blue")) +
  labs(fill = "Team") +
  guides(colour = "none")

p2 <- ggplot(data = pass_potential,aes(x = x, y = y)) + 
    geom_point(aes(color = score_prob),size=1, shape=16) +
    scale_colour_gradient2(na.value="white",low = muted("red"), mid = "white", high = muted("blue"))+#,midpoint = 0.5
    scale_x_continuous(expand = c(0, 0)) +
    scale_y_continuous(expand = c(0, 0)) +
  #geom_point(aes(x = x, y = y), size = 1, shape = 4)+
  new_scale_fill() +
  new_scale_color() +
  geom_segment(data=current_track,aes(x = x_ft, y = y_ft, xend = x_ft+vel_x, yend = y_ft+vel_y), #/sqrt(vel_x^2+vel_y^2) to get r=1
  arrow = arrow(length = unit(0.2, "cm")),size=1, colour='cyan')+
  geom_segment(aes(x = x_p, y = y_p, xend = puck$x_ft, yend = puck$y_ft),size=1.5, colour='brown')+
  geom_point(aes(x = x_p, y = y_p), size = 2, shape = 16, colour='black') +
  geom_point(data=current_track,aes(x = x_ft, y = y_ft, fill = team_name), size = 5, shape = 21) +
  geom_text(data=current_track,aes(x = x_ft, y = y_ft, label = jersey_number, colour = team_name), size = 3) +
  scale_colour_manual(values = c("Switzerland" = "white", "Finland" = "white")) +
  scale_fill_manual(values = c("Switzerland" = "red", "Finland" = "blue")) +
  labs(fill = "Team") +
  guides(colour = "none")

p3 <- ggplot(data = pass_potential,aes(x = x, y = y)) + 
    geom_point(aes(color = pass_value),size=1, shape=16) +
    scale_colour_gradient2(na.value="white",low = muted("red"), mid = "white", high = muted("blue"))+#,midpoint = 0.5
    scale_x_continuous(expand = c(0, 0)) +
    scale_y_continuous(expand = c(0, 0)) +
  #geom_point(aes(x = x, y = y), size = 1, shape = 4)+
  new_scale_fill() +
  new_scale_color() +
  geom_segment(data=current_track,aes(x = x_ft, y = y_ft, xend = x_ft+vel_x, yend = y_ft+vel_y), #/sqrt(vel_x^2+vel_y^2) to get r=1
  arrow = arrow(length = unit(0.2, "cm")),size=1, colour='cyan')+
  geom_segment(aes(x = x_p, y = y_p, xend = puck$x_ft, yend = puck$y_ft),size=1.5, colour='brown')+
  geom_point(aes(x = x_p, y = y_p), size = 2, shape = 16, colour='black') +
  geom_point(data=current_track,aes(x = x_ft, y = y_ft, fill = team_name), size = 5, shape = 21) +
  geom_text(data=current_track,aes(x = x_ft, y = y_ft, label = jersey_number, colour = team_name), size = 3) +
  scale_colour_manual(values = c("Switzerland" = "white", "Finland" = "white")) +
  scale_fill_manual(values = c("Switzerland" = "red", "Finland" = "blue")) +
  labs(fill = "Team") +
  guides(colour = "none")

p4 <- ggplot(data = pass_potential,aes(x = x, y = y)) + 
    geom_point(aes(color = adj_pass_value),size=1, shape=16) +
    scale_colour_gradient2(na.value="white",low = muted("red"), mid = "white", high = muted("blue"))+#,midpoint = 0.5
    scale_x_continuous(expand = c(0, 0)) +
    scale_y_continuous(expand = c(0, 0)) +
  #geom_point(aes(x = x, y = y), size = 1, shape = 4)+
  new_scale_fill() +
  new_scale_color() +
  geom_segment(data=current_track,aes(x = x_ft, y = y_ft, xend = x_ft+vel_x, yend = y_ft+vel_y), #/sqrt(vel_x^2+vel_y^2) to get r=1
  arrow = arrow(length = unit(0.2, "cm")),size=1, colour='cyan')+
  geom_segment(aes(x = x_p, y = y_p, xend = puck$x_ft, yend = puck$y_ft),size=1.5, colour='brown')+
  geom_point(aes(x = x_p, y = y_p), size = 2, shape = 16, colour='black') +
  geom_point(data=current_track,aes(x = x_ft, y = y_ft, fill = team_name), size = 5, shape = 21) +
  geom_text(data=current_track,aes(x = x_ft, y = y_ft, label = jersey_number, colour = team_name), size = 3) +
  scale_colour_manual(values = c("Switzerland" = "white", "Finland" = "white")) +
  scale_fill_manual(values = c("Switzerland" = "red", "Finland" = "blue")) +
  labs(fill = "Team") +
  guides(colour = "none")

p5 <- ggplot(data = pass_potential,aes(x = x, y = y)) + 
    geom_point(aes(color = off_prob),size=1, shape=16) +
    scale_colour_gradient2(na.value="white",low = muted("red"), mid = "white", high = muted("blue"))+#,midpoint = 0.5
    scale_x_continuous(expand = c(0, 0)) +
    scale_y_continuous(expand = c(0, 0)) +
  #geom_point(aes(x = x, y = y), size = 1, shape = 4)+
  new_scale_fill() +
  new_scale_color() +
  geom_segment(data=current_track,aes(x = x_ft, y = y_ft, xend = x_ft+vel_x, yend = y_ft+vel_y), #/sqrt(vel_x^2+vel_y^2) to get r=1
  arrow = arrow(length = unit(0.2, "cm")),size=1, colour='cyan')+
  geom_segment(aes(x = x_p, y = y_p, xend = puck$x_ft, yend = puck$y_ft),size=1.5, colour='brown')+
  geom_point(aes(x = x_p, y = y_p), size = 2, shape = 16, colour='black') +
  geom_point(data=current_track,aes(x = x_ft, y = y_ft, fill = team_name), size = 5, shape = 21) +
  geom_text(data=current_track,aes(x = x_ft, y = y_ft, label = jersey_number, colour = team_name), size = 3) +
  scale_colour_manual(values = c("Switzerland" = "white", "Finland" = "white")) +
  scale_fill_manual(values = c("Switzerland" = "red", "Finland" = "blue")) +
  labs(fill = "Team") +
  guides(colour = "none")

p6 <- ggplot(data = pass_potential,aes(x = x, y = y)) + 
    geom_point(aes(color = location_pass_value),size=1, shape=16) +
    scale_colour_gradient2(na.value="white",low = muted("red"), mid = "white", high = muted("blue"))+#,midpoint = 0.5
    scale_x_continuous(expand = c(0, 0)) +
    scale_y_continuous(expand = c(0, 0)) +
  #geom_point(aes(x = x, y = y), size = 1, shape = 4)+
  new_scale_fill() +
  new_scale_color() +
  geom_segment(data=current_track,aes(x = x_ft, y = y_ft, xend = x_ft+vel_x, yend = y_ft+vel_y), #/sqrt(vel_x^2+vel_y^2) to get r=1
  arrow = arrow(length = unit(0.2, "cm")),size=1, colour='cyan')+
  geom_segment(aes(x = x_p, y = y_p, xend = puck$x_ft, yend = puck$y_ft),size=1.5, colour='brown')+
  geom_point(aes(x = x_p, y = y_p), size = 2, shape = 16, colour='black') +
  geom_point(data=current_track,aes(x = x_ft, y = y_ft, fill = team_name), size = 5, shape = 21) +
  geom_text(data=current_track,aes(x = x_ft, y = y_ft, label = jersey_number, colour = team_name), size = 3) +
  scale_colour_manual(values = c("Switzerland" = "white", "Finland" = "white")) +
  scale_fill_manual(values = c("Switzerland" = "red", "Finland" = "blue")) +
  labs(fill = "Team") +
  guides(colour = "none")

p7 <- ggplot(data = pass_potential,aes(x = x, y = y)) + 
    geom_point(aes(color = keep_possesion_prob),size=1, shape=16) +
    scale_colour_gradient2(na.value="white",low = muted("red"), mid = "white", high = muted("blue"))+#,midpoint = 0.5
    scale_x_continuous(expand = c(0, 0)) +
    scale_y_continuous(expand = c(0, 0)) +
  #geom_point(aes(x = x, y = y), size = 1, shape = 4)+
  new_scale_fill() +
  new_scale_color() +
  geom_segment(data=current_track,aes(x = x_ft, y = y_ft, xend = x_ft+vel_x, yend = y_ft+vel_y), #/sqrt(vel_x^2+vel_y^2) to get r=1
  arrow = arrow(length = unit(0.2, "cm")),size=1, colour='cyan')+
  geom_segment(aes(x = x_p, y = y_p, xend = puck$x_ft, yend = puck$y_ft),size=1.5, colour='brown')+
  geom_point(aes(x = x_p, y = y_p), size = 2, shape = 16, colour='black') +
  geom_point(data=current_track,aes(x = x_ft, y = y_ft, fill = team_name), size = 5, shape = 21) +
  geom_text(data=current_track,aes(x = x_ft, y = y_ft, label = jersey_number, colour = team_name), size = 3) +
  scale_colour_manual(values = c("Switzerland" = "white", "Finland" = "white")) +
  scale_fill_manual(values = c("Switzerland" = "red", "Finland" = "blue")) +
  labs(fill = "Team") +
  guides(colour = "none")

p8 <- ggplot(data = pass_potential,aes(x = x, y = y)) + 
    geom_point(aes(color = expected_pass_value),size=1, shape=16) +
    scale_colour_gradient2(na.value="white",low = muted("red"), mid = "white", high = muted("blue"))+#,midpoint = 0.5
    scale_x_continuous(expand = c(0, 0)) +
    scale_y_continuous(expand = c(0, 0)) +
  #geom_point(aes(x = x, y = y), size = 1, shape = 4)+
  new_scale_fill() +
  new_scale_color() +
  geom_segment(data=current_track,aes(x = x_ft, y = y_ft, xend = x_ft+vel_x, yend = y_ft+vel_y), #/sqrt(vel_x^2+vel_y^2) to get r=1
  arrow = arrow(length = unit(0.2, "cm")),size=1, colour='cyan')+
  geom_segment(aes(x = x_p, y = y_p, xend = puck$x_ft, yend = puck$y_ft),size=1.5, colour='brown')+
  geom_point(aes(x = x_p, y = y_p), size = 2, shape = 16, colour='black') +
  geom_point(data=current_track,aes(x = x_ft, y = y_ft, fill = team_name), size = 5, shape = 21) +
  geom_text(data=current_track,aes(x = x_ft, y = y_ft, label = jersey_number, colour = team_name), size = 3) +
  scale_colour_manual(values = c("Switzerland" = "white", "Finland" = "white")) +
  scale_fill_manual(values = c("Switzerland" = "red", "Finland" = "blue")) +
  labs(fill = "Team") +
  guides(colour = "none")

p9 <- ggplot(data = pass_potential,aes(x = x, y = y)) + 
    geom_point(aes(color = max_pass_value),size=1, shape=16) +
    scale_colour_gradient2(na.value="white",low = muted("red"), mid = "white", high = muted("blue"))+#,midpoint = 0.5
    scale_x_continuous(expand = c(0, 0)) +
    scale_y_continuous(expand = c(0, 0)) +
  #geom_point(aes(x = x, y = y), size = 1, shape = 4)+
  new_scale_fill() +
  new_scale_color() +
  geom_segment(data=current_track,aes(x = x_ft, y = y_ft, xend = x_ft+vel_x, yend = y_ft+vel_y), #/sqrt(vel_x^2+vel_y^2) to get r=1
  arrow = arrow(length = unit(0.2, "cm")),size=1, colour='cyan')+
  geom_segment(aes(x = x_p, y = y_p, xend = puck$x_ft, yend = puck$y_ft),size=1.5, colour='brown')+
  geom_point(aes(x = x_p, y = y_p), size = 2, shape = 16, colour='black') +
  geom_point(data=current_track,aes(x = x_ft, y = y_ft, fill = team_name), size = 5, shape = 21) +
  geom_text(data=current_track,aes(x = x_ft, y = y_ft, label = jersey_number, colour = team_name), size = 3) +
  scale_colour_manual(values = c("Switzerland" = "white", "Finland" = "white")) +
  scale_fill_manual(values = c("Switzerland" = "red", "Finland" = "blue")) +
  labs(fill = "Team") +
  guides(colour = "none")

p10 <- ggplot(data = pass_potential,aes(x = x, y = y)) + 
    geom_point(aes(color = best_case_pass_value),size=1, shape=16) +
    scale_colour_gradient2(na.value="white",low = muted("red"), mid = "white", high = muted("blue"))+#,midpoint = 0.5
    scale_x_continuous(expand = c(0, 0)) +
    scale_y_continuous(expand = c(0, 0)) +
  #geom_point(aes(x = x, y = y), size = 1, shape = 4)+
  new_scale_fill() +
  new_scale_color() +
  geom_segment(data=current_track,aes(x = x_ft, y = y_ft, xend = x_ft+vel_x, yend = y_ft+vel_y), #/sqrt(vel_x^2+vel_y^2) to get r=1
  arrow = arrow(length = unit(0.2, "cm")),size=1, colour='cyan')+
  geom_segment(aes(x = x_p, y = y_p, xend = puck$x_ft, yend = puck$y_ft),size=1.5, colour='brown')+
  geom_point(aes(x = x_p, y = y_p), size = 2, shape = 16, colour='black') +
  geom_point(data=current_track,aes(x = x_ft, y = y_ft, fill = team_name), size = 5, shape = 21) +
  geom_text(data=current_track,aes(x = x_ft, y = y_ft, label = jersey_number, colour = team_name), size = 3) +
  scale_colour_manual(values = c("Switzerland" = "white", "Finland" = "white")) +
  scale_fill_manual(values = c("Switzerland" = "red", "Finland" = "blue")) +
  labs(fill = "Team") +
  guides(colour = "none")

p11 <- ggplot(data = pass_potential,aes(x = x, y = y)) + 
    geom_point(aes(color = successful_pass_prob),size=1, shape=16) +
    scale_colour_gradient2(na.value="white",low = muted("red"), mid = "white", high = muted("blue"))+#,midpoint = 0.5
    scale_x_continuous(expand = c(0, 0)) +
    scale_y_continuous(expand = c(0, 0)) +
  #geom_point(aes(x = x, y = y), size = 1, shape = 4)+
  new_scale_fill() +
  new_scale_color() +
  geom_segment(data=current_track,aes(x = x_ft, y = y_ft, xend = x_ft+vel_x, yend = y_ft+vel_y), #/sqrt(vel_x^2+vel_y^2) to get r=1
  arrow = arrow(length = unit(0.2, "cm")),size=1, colour='cyan')+
  geom_segment(aes(x = x_p, y = y_p, xend = puck$x_ft, yend = puck$y_ft),size=1.5, colour='brown')+
  geom_point(aes(x = x_p, y = y_p), size = 2, shape = 16, colour='black') +
  geom_point(data=current_track,aes(x = x_ft, y = y_ft, fill = team_name), size = 5, shape = 21) +
  geom_text(data=current_track,aes(x = x_ft, y = y_ft, label = jersey_number, colour = team_name), size = 3) +
  scale_colour_manual(values = c("Switzerland" = "white", "Finland" = "white")) +
  scale_fill_manual(values = c("Switzerland" = "red", "Finland" = "blue")) +
  labs(fill = "Team") +
  guides(colour = "none")
```

```{r}
#copy into console
require(gridExtra)
grid.arrange(point_val[[2]],plot_half_rink(p), plot_half_rink(p2),plot_half_rink(p3),plot_half_rink(p4),
plot_half_rink(p5),plot_half_rink(p6),plot_half_rink(p7),plot_half_rink(p8),
plot_half_rink(p9),plot_half_rink(p10),plot_half_rink(p11),ncol=4)
```

```{r}
#all_ctrl score_prob pass_value adj_pass_value off_prob location_pass_value keep_possesion_prob expected_pass_value max_pass_value best_case_pass_value successful_pass_prob

pdf("C:/Users/Paula/Desktop/Big-Data-Cup-2022-Private/images/all_ctrl_track406.pdf") 
plot_half_rink(p)
dev.off()
```

```{r}
load("C:/Users/Paula/Desktop/Big-Data-Cup-2022-Private/data/combine_data.Rdata")
load("C:/Users/Paula/Desktop/Big-Data-Cup-2022-Private/data/quant_columns.Rdata")

#to adjust c("adj_pass_value","location_pass_value", "expected_pass_value")
#col_2_quant <- pass_potential[,c(9,13,15)]#c(9,13,15)]
#for(ind in 1:nrow(pass_potential)){
 # col_2_quant[ind,1] <- quant_rank[which.min(abs(combine_dat[,11]-pass_potential[ind,9])),3]
  #col_2_quant[ind,2] <- quant_rank[which.min(abs(combine_dat[,15]-pass_potential[ind,13])),4]
  #col_2_quant[ind,3] <- quant_rank[which.min(abs(combine_dat[,17]-pass_potential[ind,15])),5]
#}
tic()
col_2_quant1 <- sapply(1:nrow(pass_potential), function(ind){return(quant_rank[which.min(abs(combine_dat[,11]-pass_potential[ind,9])),3])})
toc()

tic()
col_2_quant2 <- sapply(1:nrow(pass_potential), function(ind){return(quant_rank[which.min(abs(combine_dat[,15]-pass_potential[ind,13])),4])})
toc()

tic()
col_2_quant3 <- sapply(1:nrow(pass_potential), function(ind){return(quant_rank[which.min(abs(combine_dat[,17]-pass_potential[ind,15])),5])})
toc()

#pass_potential[1,c(9,13,15)]combine_dat[,c(11,15,17)]
```

```{r}
pass_potential2 <- pass_potential
pass_potential2$adj_pass_value <- col_2_quant1
pass_potential2$location_pass_value <- col_2_quant2
pass_potential2$expected_pass_value <- col_2_quant3
save(pass_potential2,file="C:/Users/Paula/Desktop/Big-Data-Cup-2022-Private/data/pass_potential_69.Rdata")

p12 <- ggplot(data = pass_potential2,aes(x = x, y = y)) + 
    geom_point(aes(color = adj_pass_value),size=2, shape=16) +
    scale_colour_gradient2(na.value="white",low = muted("green"), mid = "white", high = muted("purple"))+#,midpoint = 0.5
    scale_x_continuous(expand = c(0, 0)) +
    scale_y_continuous(expand = c(0, 0)) +
  #geom_point(aes(x = x, y = y), size = 1, shape = 4)+
  new_scale_fill() +
  new_scale_color() +
  geom_point(data=current_track,aes(x = x_ft, y = y_ft, fill = team_name), size = 5, shape = 21) +
  geom_text(data=current_track,aes(x = x_ft, y = y_ft, label = jersey_number, colour = team_name), size = 3) +
  geom_segment(aes(x = x_p, y = y_p, xend = puck$x_ft, yend = puck$y_ft),size=1.5, colour='brown')+
  geom_point(aes(x = x_p, y = y_p), size = 2, shape = 16, colour='black') +
  scale_colour_manual(values = c("USA" = "white", "Canada" = "white")) +
  scale_fill_manual(values = c("USA" = "blue", "Canada" = "red")) +
  labs(fill = "Team") +
  guides(colour = "none")+ 
  geom_segment(data=current_track,aes(x = x_ft, y = y_ft, xend = x_ft+vel_x, yend = y_ft+vel_y), #/sqrt(vel_x^2+vel_y^2) to get r=1
  arrow = arrow(length = unit(0.2, "cm")),size=1, colour='cyan')

p13 <- ggplot(data = pass_potential2,aes(x = x, y = y)) + 
    geom_point(aes(color = location_pass_value),size=2, shape=16) +
    scale_colour_gradient2(na.value="white",low = muted("green"), mid = "white", high = muted("purple"))+#,midpoint = 0.5
    scale_x_continuous(expand = c(0, 0)) +
    scale_y_continuous(expand = c(0, 0)) +
  #geom_point(aes(x = x, y = y), size = 1, shape = 4)+
  new_scale_fill() +
  new_scale_color() +
  geom_point(data=current_track,aes(x = x_ft, y = y_ft, fill = team_name), size = 5, shape = 21) +
  geom_text(data=current_track,aes(x = x_ft, y = y_ft, label = jersey_number, colour = team_name), size = 3) +
  geom_segment(aes(x = x_p, y = y_p, xend = puck$x_ft, yend = puck$y_ft),size=1.5, colour='brown')+
  geom_point(aes(x = x_p, y = y_p), size = 2, shape = 16, colour='black') +
  scale_colour_manual(values = c("USA" = "white", "Canada" = "white")) +
  scale_fill_manual(values = c("USA" = "blue", "Canada" = "red")) +
  labs(fill = "Team") +
  guides(colour = "none")+ 
  geom_segment(data=current_track,aes(x = x_ft, y = y_ft, xend = x_ft+vel_x, yend = y_ft+vel_y), #/sqrt(vel_x^2+vel_y^2) to get r=1
  arrow = arrow(length = unit(0.2, "cm")),size=1, colour='cyan')

p14 <- ggplot(data = pass_potential2,aes(x = x, y = y)) + 
    geom_point(aes(color = expected_pass_value),size=2, shape=16) +
    scale_colour_gradient2(na.value="white",low = muted("green"), mid = "white", high = muted("purple"))+#,midpoint = 0.5
    scale_x_continuous(expand = c(0, 0)) +
    scale_y_continuous(expand = c(0, 0)) +
  #geom_point(aes(x = x, y = y), size = 1, shape = 4)+
  new_scale_fill() +
  new_scale_color() +
  geom_point(data=current_track,aes(x = x_ft, y = y_ft, fill = team_name), size = 5, shape = 21) +
  geom_text(data=current_track,aes(x = x_ft, y = y_ft, label = jersey_number, colour = team_name), size = 3) +
  geom_segment(aes(x = x_p, y = y_p, xend = puck$x_ft, yend = puck$y_ft),size=1.5, colour='brown')+
  geom_point(aes(x = x_p, y = y_p), size = 2, shape = 16, colour='black') +
  scale_colour_manual(values = c("USA" = "white", "Canada" = "white")) +
  scale_fill_manual(values = c("USA" = "blue", "Canada" = "red")) +
  labs(fill = "Team") +
  guides(colour = "none")+ 
  geom_segment(data=current_track,aes(x = x_ft, y = y_ft, xend = x_ft+vel_x, yend = y_ft+vel_y), #/sqrt(vel_x^2+vel_y^2) to get r=1
  arrow = arrow(length = unit(0.2, "cm")),size=1, colour='cyan')

pdf("C:/Users/Paula/Desktop/Big-Data-Cup-2022-Private/images/adj_pass_value_quantile_track69.pdf") 
plot_half_rink(p12)
dev.off()

pdf("C:/Users/Paula/Desktop/Big-Data-Cup-2022-Private/images/location_pass_value_quantile_track69.pdf") 
plot_half_rink(p13)
dev.off()

pdf("C:/Users/Paula/Desktop/Big-Data-Cup-2022-Private/images/expected_pass_value_quantile_track69.pdf") 
plot_half_rink(p14)
dev.off()
```

```{r}
# Save a gif of the selected powerplay shot
# Note: mp4 will save in the same spot as hockey_pipeline.R, I tried to fix but couldn't get it to.
power_play <- 0
shot <- 6
save_play(dat, power_play, shot, "mp4")
```

